### PR TITLE
Add Laravel 5.8 support

### PR DESCRIPTION
**Pull request by afbora**

### CODE REVIEW

**Comment by afbora** [comment]
@kaidesu Is there any issue?

**Comment by afbora** [comment]
@kaidesu Please review the pr, thanks

**Comment by afbora** [comment]
What is the last situation?

**Comment by kaidesu** [comment]
just need some time to test - I'll get around to it, don't worry 👍

**Comment by afbora** [comment]
@kaidesu So did you test?

**Comment by kaidesu** [comment]
Sorry - we got Laravel 5.8 support in v6.0.0!

**Pull request closed without merging**
